### ISSUE TITLE
Python Source

### ISSUE THREAD

**Issue by steve-kasica** [alcantarar/ASB_Tutorial#22]
Since Python installers are a little tough to understand, I think having attendees download Python via a data science package such as Anaconda is a good idea. Its installers are pretty straight forward, but it will take a long time to download and setup. Are you guys aware of [Miniconda](https://docs.conda.io/en/latest/miniconda.html)? It's just Python and conda.

**Comment by alcantarar** [comment]
Is the full anaconda distribution required because we rely on `matplotlib` and `pandas` ? If not, I'd accept a PR updating the README. Needs to be updated with R install anyways.
