### ISSUE TITLE
Create pre-tutorial instructions

### ISSUE THREAD

**Issue by alcantarar** [alcantarar/ASB_Tutorial#5]
Attendees will need to have the following completed before jumping into the tutorial:

1. Create GitHub account
1. Download Git Bash (if PC. Mac users can use Terminal)
1. Configure Git Bash/Terminal with GitHub account (set global settings)

Ideally this is a document that we can send out to registered attendees a couple weeks before ASB. At that time, they can fill out a google form about what programming language they can use.

[This website](https://swcarpentry.github.io/git-novice/) has a pretty good introduction to git from only the command line and may be a helpful reference in creating these pre-tutorial instructions.

**Comment by GBruening** [comment]
Added instructions to install git and matlab/python to the readme. 

3013a02511d37fb99bbe4efa9438c7edcfb192e6

**Comment by GBruening** [comment]
Added just a tad more in a84776962450b669e6f2853114a6d78b6cd21be1

May want to address them cloning the repo later? But I think I going to close this for now.

**Comment by alcantarar** [comment]
@GBruening we can enable issues on a forked repository: https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork

This might be WAY overkill, but I think it might be possible to get a bot to open issues on these repositories. We could get it to open issues once certain issues are closed. Github does this with their own intro-to-github tutorial and a bot like this might work for us: https://github.com/JasonEtco/todo or https://probot.github.io/apps/gitpod/

**Comment by GBruening** [comment]
Include instructions on how to download the files and make the first initial commit so each group will be setup with their own repo before the tutorial.

**Comment by alcantarar** [comment]
@GBruening Here's a commit of my breakout_1 instructions if you wanted to reuse any of it for the group leader instructions: https://github.com/alcantarar/ASB_Tutorial/blob/6e98e2e5bfc88da0fac3920d72d4c488538ceab4/breakout_1.md . I'm going to be removing some of the info about adding collaborators, etc. since it won't be included in breakout 1 anymore, but the link is specific to a commit that had that info still in there.

**Comment by alcantarar** [comment]
@GBruening does PR https://github.com/alcantarar/ASB_Tutorial/pull/17 re-close this issue? What else needs to be done?

**Comment by GBruening** [comment]
I think we can close it.
