### ISSUE TITLE
Secure Large Meeting Zoom License

### ISSUE THREAD

**Issue by alcantarar** [alcantarar/ASB_Tutorial#7]
Need a special license from CU to host large meetings and use breakout rooms.

**Comment by alcantarar** [comment]
that was fast. got approval from IT. Also, I can pre-assign rooms before the meeting starts so we can keep people with similar programming language experience together.

**Comment by GBruening** [comment]
Yeah, with the form we can also ask people if they have people they'd prefer to work with as well.
