### ISSUE TITLE
Create Python & R Scripts

### ISSUE THREAD

**Issue by GBruening** [alcantarar/ASB_Tutorial#9]
Need to create python scripts for the people who don't have Matlab.

**Comment by alcantarar** [comment]
This will depend on feedback from #10 (pre-tutorial survey)

**Comment by steve-kasica** [comment]
You can assign this to me if you want to port your MatLab script to Python or R.

**Comment by GBruening** [comment]
I think i got most of the python scripts done in 38d8b0b2c25fe2eac090fda722e6262d0be4d0e7

Though there is still a bug with the plotting the leaf.

If you wanna do the R scripts that'd be awesome.

**Comment by alcantarar** [comment]
Although having copies of the tutorial exercises in an open source language will be an overall benefit (and may be enough motivation for you to port it to R), you can also wait until we get the pre-tutorial survey results back to see if they will actually be needed. Surveys should go out this weekend.

**Comment by alcantarar** [comment]
About half of the surveys have been filled out so far and everyone will be able to use MATLAB except for 1 person who can only use R. There are other people who can do R or MATLAB so we should be able to have one group of attendees be the "R group". 

@swkasica can you start porting the scripts to R to accommodate this attendee? Gary's PR #20 for the 3rd breakout room isn't ready to merge yet and will technically block you from finishing the R port, but you can branch off `master`, port `main_script.m` and the subscripts for breakout 1/2, adding a section for breakout 3 when it's finalized... or just wait until #20 is merged. I'll @ you when it happens.

**Comment by alcantarar** [comment]
Now there's 1 person who can only use python. @GBruening @swkasica here's how I suggest we divide and conquer this:

Steve, port the matlab code to R and refactor the python code Gary has written, prioritizing python 2/3 compatibility and minimizng the work users need to do to get the scripts up and running. Be aware that there is a plotting component of the tutorial.

Gary, finish up the 3rd breakout room materials (PR #20). This is the top priority as it is blocking us from actually doing a run-through of the interactive parts of this tutorial. A run through is necessary so we can adjust content and stay within the 90-min timeframe.

**Comment by steve-kasica** [comment]
I'm nearly done with the Python scripts. I haven't started on the R scripts, but I think there's plenty of time to finish it before EOD Wednesday.

**Comment by steve-kasica** [comment]
Ok, I'm going to work on the R scripts now. I've just got the change the `.py` extensions to `.R` right?
